### ISSUE TITLE
Retry with backoff

### ISSUE THREAD

**Issue by fedeisas** [AgencyPMG/Queue#58]
I think it would be cool if retries can have delay. Somethig like this:

```php
final class BackoffSpec extends LimitedSpec
{
    public function getDelay(Envelope $env) {
        return $env->attempts() ** 3;
    }
}
```

**Comment by chrisguitarguy** [comment]
> I think it would be cool if retries can have delay.

Agreed!

But I think that would have to happen in the driver somehow -- not all queue backends will support a delay as nicely as beanstalkd does.

**Comment by chrisguitarguy** [comment]
Sorry for the delay here, @shadowhand 

> Can someone from PMG give a little detail on how this might be implemented?

Basically I think that the consumer shouldn't care about a back off as that's a feature of the underlying driver. The consumer doesn't care that it's doesn't get a message for X minutes because its delayed, it just cares that it can interact with its driver.

So something like the Pheanstalk driver could be fleshed out with a real options object instead of an [array of options values](https://github.com/AgencyPMG/queue-pheanstalk/blob/de61d2868ba01b19322a5953df1dc427217be0ff/src/PheanstalkDriver.php#L55-L66) that could calculate a backoff.

But maybe the backoff calculation stuff itself belongs in the core with its own interface and set of implementations.

```php
namespace PMG\Queue;

interface DelayStrategy
{
  /**
   * @param $env The envelop being retried
   * @return The retry delay in seconds
   */
  public function retryDelayFor(Envelope $env) : int
}
```

Some implementation that should probably be provied:

- static value (including a named constructor for no delay)
- Exponential delay described by @fedeisas in the original issue here

**Comment by shadowhand** [comment]
I think it makes the most sense to add to the `RetrySpec` so that it can specify the delay:

```php
public function retryDelay(Envelope $env): int;
```

This would be documented as something like:

> If the queue driver supports delaying, the message will be put back into the queue after the specified number of seconds.

**Comment by shadowhand** [comment]
See PR that I just added. This is obviously a breaking change, and it assumes that retry delay will simply be ignored by drivers that do not support it, which may or may not be desirable.

**Comment by chrisguitarguy** [comment]
This was in #79 

I had a bit of an idea on how it could be integrated with drivers. Instead of passing a delay parameter to `Driver::retry`, we could add a `$delay` property to the `Envelope` interface/implementation. 

This means stuff like this happens:

```php
$envelope->retry($this->retries->retryDelay($envelope)); // awkward-ish
```
And, more interestingly, the driver could respect delays when a message is enqueued the first time.

Thoughts?

**Comment by shadowhand** [comment]
So this means that envelope itself would hold the retry state? I can definitely see benefits to that, namely that different envelopes could have specific priority.

**Comment by chrisguitarguy** [comment]
The envelope already holds part of the rety state (like the number of attempts), this is just adding the delay as well.

Envelope is an internal interface, though, so I could see additional methods being added to the producer to better support a delay feature.

```php
interface Producer
{
  public function send(Message $message);

  public function delay(Message $message, int $seconds);
}
```

**Comment by shadowhand** [comment]
I'm not really keep on the `Producer::delay()` method. For me the end goal is always going to be: retry needs to slow down every time a message fails.

**Comment by chrisguitarguy** [comment]
Sure, that's still the result here. But keeping a delay in the envelope provides some other options, basically.
